services:
  - type: web
    name: saeam-portfolio
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: redirect
        source: /about/
        destination: /about
        permanent: true
      - type: redirect
        source: /grail-telemedicine/
        destination: /grail-telemedicine
        permanent: true
      - type: redirect
        source: /grail-clinical/
        destination: /grail-clinical
        permanent: true
      - type: redirect
        source: /axlehire-driver/
        destination: /axlehire-driver
        permanent: true
      - type: redirect
        source: /axlehire-client/
        destination: /axlehire-client
        permanent: true
